# Basic Information
title: "Matteo Stromieri"
position: "PhD student"
affiliation: "University of Haifa, INRIA"
email: "matt.stromieri@gmail.com"

# Search Engine Optimization (SEO)
keywords: "Matteo Stromieri"
description: "Matteo Stromieri personal research website"
canonical: "https://minimal-light-theme.yliu.me/"

# Links
google_scholar: "https://scholar.google.com/citations?user=KVrWdscAAAAJ&hl=en"
# cv_link: "assets/files/curriculum_vitae.pdf"
github_link: "https://github.com/MatteoStromieri"
linkedin: "https://it.linkedin.com/in/matteo-stromieri-8336a31b8"
# twitter: "https://twitter.com/"

# Images
avatar: "./assets/img/avatar.png"
favicon: "./assets/img/favicon.png"
favicon_dark: "./assets/img/favicon-dark.png"

# Footnote
enable_footnote: false

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif" # or "Sans Serif"

# Google Analytics ID
google_analytics: "UA-111540567-4"

# Remote Theme
remote_theme: "yaoyao-liu/minimal-light"

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
